version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localeventorganizer-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: localeventorganizer
      DB_USERNAME: root
      DB_PASSWORD: Motionless@123
      # Aggressive PHP-FPM optimizations
      PHP_MEMORY_LIMIT: 1G
      PHP_MAX_EXECUTION_TIME: 300
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_MEMORY_CONSUMPTION: 512
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      PHP_OPCACHE_FAST_SHUTDOWN: 1
      PHP_REALPATH_CACHE_SIZE: 8192K
      PHP_REALPATH_CACHE_TTL: 1200
      PHP_MAX_INPUT_VARS: 3000
      PHP_POST_MAX_SIZE: 100M
      PHP_UPLOAD_MAX_FILESIZE: 100M
    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules
      - ./storage:/var/www/storage:delegated
      - ./bootstrap/cache:/var/www/bootstrap/cache:delegated
    command: sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && chmod -R 777 /var/www/storage /var/www/bootstrap/cache && php artisan optimize && php artisan view:cache && php artisan config:cache && php artisan route:cache && npm run dev -- --host & php-fpm"
    ports:
      - "5173:5173"
      - "5174:5174"
    networks:
      - localevent
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  nginx:
    image: nginx:alpine
    container_name: localeventorganizer-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      # Aggressive Nginx optimizations
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=4096
      - NGINX_KEEPALIVE_TIMEOUT=120
      - NGINX_KEEPALIVE_REQUESTS=200
      - NGINX_SENDFILE=on
      - NGINX_TCP_NOPUSH=on
      - NGINX_TCP_NODELAY=on
      - NGINX_OPEN_FILE_CACHE=on
      - NGINX_OPEN_FILE_CACHE_VALID=60s
      - NGINX_OPEN_FILE_CACHE_MIN_USES=1
      - NGINX_OPEN_FILE_CACHE_ERRORS=on
    networks:
      - localevent
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  db:
    image: mysql:8.0
    container_name: localeventorganizer-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: localeventorganizer
      MYSQL_ROOT_PASSWORD: Motionless@123
      MYSQL_PASSWORD: Motionless@123
      # Aggressive MySQL optimizations
      MYSQL_INNODB_BUFFER_POOL_SIZE: 1G
      MYSQL_INNODB_LOG_FILE_SIZE: 256M
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 2
      MYSQL_INNODB_FLUSH_METHOD: O_DIRECT
      MYSQL_INNODB_IO_CAPACITY: 4000
      MYSQL_INNODB_READ_IO_THREADS: 8
      MYSQL_INNODB_WRITE_IO_THREADS: 8
      MYSQL_INNODB_BUFFER_POOL_INSTANCES: 8
      MYSQL_INNODB_THREAD_CONCURRENCY: 0
      MYSQL_INNODB_READ_AHEAD_THRESHOLD: 56
      MYSQL_INNODB_RANDOM_READ_AHEAD: 0
      MYSQL_INNODB_STATS_ON_METADATA: 0
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=256M
      --innodb-flush-method=O_DIRECT
      --innodb-io-capacity=4000
      --innodb-read-io-threads=8
      --innodb-write-io-threads=8
      --innodb-flush-log-at-trx-commit=2
      --innodb-buffer-pool-instances=8
      --innodb-thread-concurrency=0
      --innodb-read-ahead-threshold=56
      --innodb-random-read-ahead=0
      --innodb-stats-on-metadata=0
      --innodb-file-per-table=1
      --innodb-flush-neighbors=0
      --innodb-strict-mode=0
    ports:
      - "4306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - localevent
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: localeventorganizer-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Motionless@123
      # PhpMyAdmin optimizations
      UPLOAD_LIMIT: 500M
      MEMORY_LIMIT: 512M
    ports:
      - "8081:80"
    networks:
      - localevent
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  localevent:
    driver: bridge

volumes:
  dbdata:
    driver: local